module.exports = road => {

  road
    .extension('debug', require('lr-debug')('f1manager'))
    .middleware({
      'general.debug' : require('../middleware/debug')
    })
    .where('apiserver')
      .path('circuits', '/circuits')
      .path('chassis', '/chassis')
      .path('drivers', '/drivers')
      .path('engines', '/engines')
      .path('predictions', '/predictions')
      .path('results', '/results')
      .path('standings', '/standings')
      .path('statistics', '/statistics')
      .path('teams', '/teams')
    .where('webserver', 'client')
      .path('rules', '/rules')
      .path('newTeam', '/team/new')
      .path('editTeam', '/team/edit/:id')
      .path('predictions', '/predictions')
      .path('results', '/results')
      .path('standings', '/standings')
      .path('statistics', '/statistics')
      .path('teams', '/teams')
    .where('webserver')
      .path('login', '/')
      .path('logout', '/logout')
      .path('githubConsent', '/auth/github')
      .path('githubToken', '/auth/github/callback')
      .path('facebookConsent', '/auth/facebook')
      .path('facebookToken', '/auth/facebook/callback')
      .path('googleConsent', '/auth/google')
      .path('googleToken', '/auth/google/callback')
      .pathGroup('auth', 'logout', 'githubToken', 'githubConsent', 'facebookToken', 'facebookConsent', 'googleToken', 'googleConsent')
      .pathGroup('authAndLogin', 'auth', 'login')
    .where('webserver', 'apiserver', 'client')
      .run('*', 'general.debug')
    .where('webserver')
      .run('-auth', 'general.statics')
      .run('-auth', 'parsers.cookies')
      .run('-auth', 'parsers.token')
      .run('-auth', 'parsers.decrypt')
      .run('-auth', 'request.userByToken')
      .run('-authAndLogin', 'login.check')
      .run('login', 'login.redirect')
      .run('login', 'templating.layout.login')
      .run('-login', 'templating.layout.default')
      .run('-authAndLogin', 'request.teamsByUserId')
      .run('-authAndLogin', 'templating.loaded.navigation')
    .where('client')
      .run('teams', 'templating.loading.teams')
      .run('newTeam', 'templating.loading.team')
      .run('editTeam', 'templating.loading.team')
      .run('predictions', 'templating.loading.prediction')
    .where('webserver', 'client')
      .run('teams', 'request.teams')
      .run('teams', 'templating.failed.general')
      .run('teams', 'prepare.teams')
      .run('teams', 'templating.loaded.teams')
      .run('teams', 'events.teams')
