module.exports = road => {

  road
  .where('webserver', 'apiserver', 'client')
    .events('router', 'get', 'post')
  .where('webserver', 'client')
    .events('api', 'request')
    .listen('request', 'get', 'post')
  .where('client')
    .events('renderer', 'added')
    .listen('get', 'request')
  .where('apiserver')
    .path('circuits', '/circuits')
    .path('chassis', '/chassis')
    .path('drivers', '/drivers')
    .path('engines', '/engines')
    .path('predictions', '/predictions')
    .path('results', '/results')
    .path('standings', '/standings')
    .path('statistics', '/statistics')
    .path('teams', '/teams')
  .where('webserver', '/client')
    .path('rules', '/rules')
    .path('newTeam', '/team/new')
    .path('editTeam', '/team/edit/:id')
    .path('predictions', '/predictions')
    .path('results', '/results')
    .path('standings', '/standings')
    .path('statistics', '/statistics')
    .path('teams', '/teams')
  .where('webserver')
    .path('login', '/')
    .path('logout', '/logout')
    .path('githubConsent', '/auth/github')
    .path('githubToken', '/auth/github/callback')
    .path('facebookConsent', '/auth/facebook')
    .path('facebookToken', '/auth/facebook/callback')
    .path('googleConsent', '/auth/google')
    .path('googleToken', '/auth/google/callback')
    .pathGroup('auth', 'logout', 'githubToken', 'githubConsent', 'facebookToken', 'facebookConsent', 'googleToken', 'googleConsent')
    .pathGroup('authAndLogin', 'auth', 'login')
  .where('webserver')
    .get('-auth', 'helpers.statics')
    .get('-auth', 'parsers.cookies')
    .get('-auth', 'parsers.token')
    .get('-auth', 'parsers.decrypt')
    .request('-auth', 'userByToken', 'token')
    .get('-authAndLogin', 'login.check')
    .get('login', 'login.redirect')
    .get('login', 'template.layout', 'login')
    .get('-login', 'template.layout', 'default')
    .request('-authAndLogin', 'teamsByUserId', 'user.id')
    .get('-authAndLogin', 'templating.build', 'navigation', 'me', 'myTeams')
    .get('-authAndLogin', 'templating.render', 'navigation', '#menu')
